#!/bin/bash
# A simple script to pack and sign your installer zip
# Delete temporary "~" files; reduce clutter, make zip files cleaner
find . -name "*~" -type f -delete
zip -r r_temp.zip extract/ META-INF/   >/dev/null 2>/dev/null
java -Xmx2048m -jar signing/signapk.jar -w signing/testkey.x509.pem signing/testkey.pk8 r_temp.zip r_signapk.zip   >/dev/null 2>/dev/null
./signing/zipadjust r_signapk.zip r_aligned.zip
java -Xmx2048m -jar signing/minsignapk.jar signing/testkey.x509.pem signing/testkey.pk8 r_aligned.zip r.zip
rm -rf r_signapk.zip r_aligned.zip r_temp.zip
