#!/bin/bash
# A simple script to pack and sign your installer zip
# Delete temporary "~" files; reduce clutter, make zip files cleaner
find . -name "*~" -type f -delete
zip -r r.zip extract/ META-INF/   >/dev/null 2>/dev/null
